### ISSUE TITLE
How to handle "Config command failed waiting on input"

### ISSUE THREAD

**Issue by sreerajkksd** [ekkis/cpan2rpm#9]
I tried to build a good number of perl packages to RPM using cpan2rpm and it works totally  fine.

I noticed an error "Config command failed waiting on input." common while building some packages like 
 Net::SSH::Perl, Spreadsheet::Read and Chart::Graph. Expected input is different for different packages, I couldn't find a documented approach to fix this. Is this something that I can fix using "--config" option ?

here is a simple reproducer:
```
cpantorpm --debug -T vendor --clean-macros 'Net::SSH::Perl'
```

**Comment by ekkis** [comment]
to be honest, I haven't touched this in so long I no longer remember how it works so you might need to experiment a bit

**Comment by clayne** [comment]
@sreerajkksd You have the wrong project. This is `cpan2rpm`, not [`cpantorpm`](https://metacpan.org/dist/App-CPANtoRPM/view/bin/cpantorpm.pod).
@ekkis Might as well close :-)

**Comment by ekkis** [comment]
thanks @clayne
